<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-28T15:53:11 EDT" name="Surefire suite" finished-at="2021-10-28T15:53:21 EDT" duration-ms="10193">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner@57f23557]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2021-10-28T15:53:11 EDT" name="Surefire test" finished-at="2021-10-28T15:53:21 EDT" duration-ms="10193">
      <class name="TestRunner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:TestRunner@57f23557]" started-at="2021-10-28T15:53:11 EDT" name="setUpClass" finished-at="2021-10-28T15:53:12 EDT" duration-ms="537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner@57f23557]" started-at="2021-10-28T15:53:12 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2021-10-28T15:53:21 EDT" duration-ms="9494" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Student should be able to register with valid information"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Sign up]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageObject.signupPage.getThankYouMessage(signupPage.java:155)
at stepDef.signupStep.iShouldSeeThankYouForSignUpMessage(signupStep.java:45)
at âœ½.I should see Thank you for sign up message(file:///Users/jannatulnayeem/Documents/QA_Automation/GitProject/CucumberBDD_June2021/src/test/java/feature/signup.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunner@57f23557]" started-at="2021-10-28T15:53:21 EDT" name="tearDownClass" finished-at="2021-10-28T15:53:21 EDT" duration-ms="111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
