<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jannats-Air.fios-router.home" failures="1" tests="1" name="TestRunner" time="9.494" errors="0" timestamp="2021-10-28T15:53:21 EDT" skipped="0">
  <testcase classname="TestRunner" name="runScenario" time="9.494">
    <failure message="expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageObject.signupPage.getThankYouMessage(signupPage.java:155)
at stepDef.signupStep.iShouldSeeThankYouForSignUpMessage(signupStep.java:45)
at âœ½.I should see Thank you for sign up message(file:///Users/jannatulnayeem/Documents/QA_Automation/GitProject/CucumberBDD_June2021/src/test/java/feature/signup.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- TestRunner -->
